# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd

script:
    - hugo -d blog
    - echo 'Hugo build done!'
after_success:
    - git config --global user.email "qfq61@qq.com"
    - git config --global user.name "QFQ"
    - git clone https://$GithubToken@github.com/tainzhi/tainzhi.github.io.git container
    - rm -rf container/blog
    - cp -r blog container 
    - cd container
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin master
    # Github Pages
    - git push --force --quiet "https://${CodingNetToken}@${Github_REF}" master:master 
    # Coding Pages
    - git push --force --quiet "https://qinyuanpei:${CodingNetToken}@${CodingNetToken}" master:master
    - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
    # Github Pages
    - git push --quiet "https://${CodingNetToken}@${Github_REF}" master:master --tags
    # Coding Pages
    - git push --quiet "https://qinyuanpei:${CodingNetToken}@${CodingNetToken}" master:master --tags
env:
 global:
   # Github Pages
   - Github_REF: github.com/tainzhi/tainzhi.github.io
   # Coding Pages
   - CodingNet_REF: git.coding.net/qfq/qfq.coding.me.git
