# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd

script:
    - hugo
    - echo 'Hugo build done!'
after_success:
    - git config --global user.email "qfq61@qq.com"
    - git config --global user.name "QFQ"gi
    # Gihub pages
    - rm github-pages
    - git clone https://${GithubToken}@${Github_REF} github-pages
    - rm github-pages/* -rf
    - cp public github-pages -rf
    - cd github-pages
    - pwd
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push --force --quiet https://${CodingNetToken}@${Github_REF} master:master 
    - cd ..
    # Coding.net pages
    - rm coding-pages
    - git clone https://${CodingNetToken}@{CodingNet_REF} coding-pages
    - cp public coding-pages
    - cd coding-pages
    - ls
    - git add .
    - git commit -m 'Travis update'
    - git push --force --quiet https://${CodingNetToken}@${CodingNet_REF} master:master
env:
 global:
   # Github Pages
   - Github_REF: github.com/tainzhi/tainzhi.github.io.git
   # Coding Pages
   - CodingNet_REF: git.coding.net/qfq/qfq.coding.me.git
