# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd

script:
    - hugo
    - echo 'Hugo build done!'
after_success:
  - cd ./public
  - git init
  - git config user.name "QFQ"
  - git config user.email "qfq61@qq.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://tainzhi:${GithubToken}@${Github_REF}" master:master 
  - git push --quiet "https://tainzhi:${GithubToken}@${GithubToken}" master:master --tags
  # Coding Pages
  - git push --force --quiet "https://qfq:${CodingNetToken}@${CodingNet_REF}" master:master
  - git push --quiet "https://qfq:${CodingNetToken}@${CodingNet_REF}" master:master --tags
  # Github Pages

env:
 global:
   # Github Pages
   #https://github.com/tainzhi/tainzhi.github.io.git
   #git@github.com:tainzhi/tainzhi.github.io.git
   - Github_REF: github.com/tainzhi/tainzhi.github.io.git
   # Coding Pages
   #https://git.coding.net/qfq/qfq.coding.me.git
   #git@git.coding.net:qfq/qfq.coding.me.git
   - CodingNet_REF: git.coding.net/qfq/qfq.coding.me.git
