# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - ls
    - pwd

script:
    - hugo
    - echo 'Hugo build done!'
after_script:
  - git clone "https://tainzhi:${GithubNetToken}@${GithubNet_REF}" github-pages
  - rm github-pages/public -rf
  - cp ./public/* github-pages -rf
  - cd github-pages
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://tainzhi:${GithubToken}@${Github_REF}" master:master 
  - git push --quiet "https://tainzhi:${GithubToken}@${Github_REF}" master:master --tags
  # Coding Pages
  - git push --force --quiet "https://qfq:${CodingNetToken}@${CodingNet_REF}" master:master
  - git push --quiet "https://qfq:${CodingNetToken}@${CodingNet_REF}" master:master --tags
# deploy:
  # local_dir: public # Default static site output dir for Hugo
  # repo: tainzhi/tainzhi.github.io # This is the slug of the repo you want to deploy your site to
  # target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  # provider: pages
  # skip_cleanup: true
  # github_token: $GithubToken # This is the authentication which you will setup in the next step in travis-ci dashboard
  # email: qfq61@qq.com
  # name: "qfq"
  # on:
    # branch: master

env:
 global:
   # Github Pages
   #https://github.com/tainzhi/tainzhi.github.io.git
   #git@github.com:tainzhi/tainzhi.github.io.git
   - Github_REF: github.com/tainzhi/tainzhi.github.io.git
   # Coding Pages
   #https://git.coding.net/qfq/qfq.coding.me.git
   #git@git.coding.net:qfq/qfq.coding.me.git
   - CodingNet_REF: git.coding.net/qfq/qfq.coding.me.git
